// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/koddr/template-microservice-go/internal/application"
	"github.com/koddr/template-microservice-go/internal/attachments"
	"github.com/koddr/template-microservice-go/internal/config"
	"github.com/koddr/template-microservice-go/internal/database"
)

// Injectors from wire.go:

// initializeApplication provides the dependency injection process by the "google/wire" package.
func initializeApplication() (*application.Application, error) {
	attachmentsAttachments := attachments.New()
	configConfig := config.New()
	databaseDatabase, err := database.New(configConfig)
	if err != nil {
		return nil, err
	}
	applicationApplication := application.New(attachmentsAttachments, configConfig, databaseDatabase)
	return applicationApplication, nil
}
